# Generated by Django 3.1.4 on 2020-12-08 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='DOB',
            field=models.DateField(default=datetime.date(2020, 12, 8)),
        ),
    ]
