# Generated by Django 3.1.4 on 2020-12-10 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='DOB',
            field=models.DateField(default=datetime.date(2020, 12, 10)),
        ),
    ]
